### ISSUE TITLE
一个发生的错误

### ISSUE THREAD

**Issue by fanzwd** [lefex/TCZLocalizableTool#2]
执行报错：

```
wf.write(value.replace(DESPATH, '') + '\n')
ValueError: I/O operation on closed file
```

在images也只有一个文件

注释掉136行的 wf.close() 就不报错，不懂py，也许说错了什么

**Comment by lefex** [comment]
你的 DESPATH 是什么？

**Comment by blackchena** [comment]
我也遇到这样的错误 DESPATH 为我的项目路径/Users/\*\*\*/Documents/\*\*\*\*-\*\*\*\* 项目路径文件名中有一个‘-’不知道是不是这个原因

**Comment by fanzwd** [comment]
这是我的路径
/Users/userName/Desktop/workspaceName
我的工作空间里面包含多个project
不知道这个会不会有影响

**Comment by lefex** [comment]
已修改
