### ISSUE TITLE
[完善]查找项目里面没有国际化的字符串

### ISSUE THREAD

**Issue by hummersoftware** [lefex/TCZLocalizableTool#5]
能否找出项目中国际化的字符串，但是在.strings里面没有？
例如，在工程中写了NSLocalizedString(@"Common.OK", nil)，但是在.strings里面没有定义
"Common.OK" = "OK",
这种情况 unLocalizable.py 找不出来；希望能改进优化。

**Comment by lefex** [comment]
这个主要是匹配 NSLocalizedString(@"汉语") 以汉语为条件的，它会把 NSLocalizedString(@"Common.OK", nil) 识别成已国际化文字。如果改了，即使是已国际化的也会被当作未国际化的处理。所有可以自行改脚本，满足特殊的项目需求。
